### ISSUE TITLE
dettagli schema

### ISSUE THREAD

**Issue by alexcappelletti** [AlessandroRizzetto/RT_HAI#1]
su arduino NANO su tutti i digital out (GPIO) la tensione massima é di 5V mentre su NodeMCU v3 sono a 3.3V
nel layout del circuito relativo al motore non é chiaro dove va messo il  pin +5v

**Comment by Simone-io** [comment]
Per quanto riguarda il discorso dei 5V-3.3V non penso che ci siano problemi, dato che i motorini di vibrazione consumano poco. In caso bisognerà fare dei test.
Invece per il secondo problema ora ho generalizzato lo schema elettrico.
Infine ho aggiornato la mappatura del pinout per l'ESP32 nel commit 63f3e7dda76ddb27c88475463e550cd382e4be58.
